### ISSUE TITLE
Grid based service selection screen (legal issue screen):

### ISSUE THREAD

**Issue by bahlahkay** [Digital-Law-Lab/docassemble-LLAW33012020S2P06#6]
* Selecting a service should be grid-based much like the iRefer app (big pictures max 2 columns).
* Domestic Violence (DV) should be at the top.
* Family Law after DV.

**Comment by bahlahkay** [comment]
Not possible with the buttons field type if want to select multiple issues.

Buttons field to give the appearance of tiles only allows for single selection of items.

Besides checkboxes, the other multiselect option is this: https://docassemble.org/docs/fields.html#fields%20multiselect
Note that the way checkboxes are implemented in docassemble, the actual HTML checkbox <input> element is hidden by JavaScript and the  <label> elements have the styling of Bootstrap buttons. CSS is used to show or hide different <span> elements depending on whether the checkbox is checked. JavaScript toggles between btn-light and btn-primary on the <label>.
You could add some CSS classes to hide the check marks and then maybe it would be more like what you are envisioning. E.g., you could remove display: table and width: 100% and then the buttons would wrap.

Next version of docassemble may viable workaround built in for multiselect with buttons:
![image](https://user-images.githubusercontent.com/36625142/177951899-3d6e45c4-975a-41d1-bc7b-b7c812eb9731.png)

[Quinten Steenhuis](https://app.slack.com/team/U78UWL07L)
  [8 days ago](https://docassemble.slack.com/archives/C7791ATUJ/p1656613889508659?thread_ts=1656590496.224339&cid=C7791ATUJ)
[@Bryce Willey](https://docassemble.slack.com/team/U01FT96LG1Z)
 and I did a project where we re-styled the ``multiselect` input with JavaScript and CSS
https://apps.chancerylaneproject.org/
https://github.com/LemmaLegalConsulting/docassemble-tclpgoogledocsmerger
There was an open source library that got us a lot of the way there, that was built around the multiselect input. that was really helpful
GitHubGitHub
[GitHub - LemmaLegalConsulting/docassemble-tclpgoogledocsmerger: A docassemble extension.](https://github.com/LemmaLegalConsulting/docassemble-tclpgoogledocsmerger)
A docassemble extension. Contribute to LemmaLegalConsulting/docassemble-tclpgoogledocsmerger development by creating an account on GitHub. (70 kB)

**Comment by Sirage-t** [comment]
The way I had implemented something similar in a previous project is by using checkboxes and hiding them with JavaScript. Once JavaScript takes over you could render almost anything.
